// Generated by CoffeeScript 1.6.3
/*
Easy pie chart is a jquery plugin to display simple animated pie charts for only one value

Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php)
and GPL (http://www.opensource.org/licenses/gpl-license.php) licenses.

Built on top of the jQuery library (http://jquery.com)

@source: http://github.com/rendro/easy-pie-chart/
@autor: Robert Fleischmann
@version: 1.2.3

Inspired by: http://dribbble.com/shots/631074-Simple-Pie-Charts-II?list=popular&offset=210
Thanks to Philip Thrasher for the jquery plugin boilerplate for coffee script
*/

let value_aqi;

showAqi();
showTemp();

setInterval(function() {showAqi()}, 1000);
setInterval(function() {showTemp()}, 1000);

function showTemp() {
  const xhttp1 = new XMLHttpRequest();
  xhttp1.onload = function() {
    document.getElementById("temp").innerHTML =
    this.responseText + "&#8451;";
  }
  xhttp1.open("GET", "getTemp.php");
  xhttp1.send();   
}

function showAqi() {
  const xhttp = new XMLHttpRequest();
  xhttp.onload = function() {
    document.getElementById("aqi").innerHTML =
    this.responseText;
    value_aqi = parseInt(this.responseText);
    if(value_aqi <= 50)
    {
      $("body").css("background-color","#006400");
      document.getElementById('infor1').style.backgroundColor = "#005200";
      document.getElementById('infor2').style.backgroundColor = "#005200";
      document.getElementById("status").innerHTML = "Good";
      document.getElementById("status_describe").innerHTML = "Air quality is satisfactory, and air pollution poses little or no risk.";
    }
    else if (value_aqi > 50 && value_aqi <= 100)
    {
      $("body").css("background-color","#CCCC00");
      document.getElementById('infor1').style.backgroundColor = "#A2A205";
      document.getElementById('infor2').style.backgroundColor = "#A2A205";
      document.getElementById("status").innerHTML = "Moderate";
      document.getElementById("status_describe").innerHTML = "Air quality is acceptable. However, there may be a risk for some people, particularly those who are unusually sensitive to air pollution.";
    }
    else if (value_aqi > 100 && value_aqi <= 150)
    {
      $("body").css("background-color","#F79327");
      document.getElementById('infor1').style.backgroundColor = "#C46F0E";
      document.getElementById('infor2').style.backgroundColor = "#C46F0E";
      document.getElementById("status").innerHTML = "Unhealthy for Sensitive Groups";
      document.getElementById("status_describe").innerHTML = "Members of sensitive groups may experience health effects. The general public is less likely to be affected.";
    }
    else if (value_aqi > 150 && value_aqi <= 200)
    {
      $("body").css("background-color","#B70404");
      document.getElementById('infor1').style.backgroundColor = "#920303";
      document.getElementById('infor2').style.backgroundColor = "#920303";
      document.getElementById("status").innerHTML = "Unhealthy";
      document.getElementById("status_describe").innerHTML = "Some members of the general public may experience health effects; members of sensitive groups may experience more serious health effects.";
    }
    else if (value_aqi > 200 && value_aqi <= 300)
    {
      $("body").css("background-color","#400E32");
      document.getElementById('infor1').style.backgroundColor = "#44213A";
      document.getElementById('infor2').style.backgroundColor = "#44213A";
      document.getElementById("status").innerHTML = "Very Unhealthy";
      document.getElementById("status_describe").innerHTML = "Health alert: The risk of health effects is increased for everyone.";
    }
    else
    {
      $("body").css("background-color","#520101");
      document.getElementById('infor1').style.backgroundColor = "#400101";
      document.getElementById('infor2').style.backgroundColor = "#400101";
      document.getElementById("status").innerHTML = "Hazardous";
      document.getElementById("status_describe").innerHTML = "Health warning of emergency conditions: everyone is more likely to be affected.";
    }
  }
  xhttp.open("GET", "getAqi.php");
  xhttp.send();   
}

function startTime() {
  const today = new Date();
  let h = today.getHours();
  let m = today.getMinutes();
  let s = today.getSeconds();
  m = checkTime(m);
  s = checkTime(s);
  document.getElementById('timeid').innerHTML =  h + " : " + m + " : " + s;
  setTimeout(startTime, 1000);
}

function checkTime(i) {
  if (i < 10) {i = "0" + i};  // add zero in front of numbers < 10
  return i;
}











